[build]
  base = "/"
  command = "cd rendering && npm install && npm run build"
  publish = "rendering/dist"

[build.environment]
  NODE_VERSION = "18"

# Ensure clean URLs
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 