/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}",
    "./node_modules/preline/preline.js",
  ],
  darkMode: "class",
  future: {
    hoverOnlyWhenSupported: true,
    respectDefaultRingColorOpacity: true,
    disableColorOpacityUtilitiesByDefault: true,
    relativeContentPathsByDefault: true,
  },
  theme: {
    extend: {
      screens: {
        xs: "475px",
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
        "2xl": "1536px",
      },
      container: {
        center: true,
        padding: {
          DEFAULT: "1rem",
          sm: "2rem",
          lg: "4rem",
          xl: "5rem",
          "2xl": "6rem",
        },
      },
      colors: {
        first: "#383877", // Main first color (previously primary)
        second: "#ea580c", // Main second color (previously secondary)
        third: "#1f2937", // Optional third color
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        heading: ["Poppins", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-2xl": ["4.5rem", { lineHeight: "1.1" }],
        "display-xl": ["3.75rem", { lineHeight: "1.1" }],
        "display-lg": ["3rem", { lineHeight: "1.1" }],
        "display-md": ["2.25rem", { lineHeight: "1.2" }],
        "display-sm": ["1.875rem", { lineHeight: "1.2" }],
      },
      boxShadow: {
        "soft-xl": "0 20px 27px rgba(0, 0, 0, 0.05)",
        "soft-lg": "0 10px 15px rgba(0, 0, 0, 0.05)",
        "soft-md": "0 4px 7px rgba(0, 0, 0, 0.05)",
        "soft-sm": "0 2px 4px rgba(0, 0, 0, 0.05)",
      },
      animation: {
        "fade-in": "fadeIn 0.5s ease-in-out",
        "slide-up": "slideUp 0.5s ease-in-out",
        "slide-down": "slideDown 0.5s ease-in-out",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { transform: "translateY(10px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        slideDown: {
          "0%": { transform: "translateY(-10px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/typography"),
  ],
  corePlugins: {
    float: true,
    clear: true,
    skew: true,
    rotate: true,
    scale: true,
    translate: true,
    transform: true,
    transformOrigin: true,
    perspective: true,
    perspectiveOrigin: true,
    backfaceVisibility: true,
    backgroundAttachment: true,
    backgroundClip: true,
    backgroundImage: true,
    backgroundOrigin: true,
    backgroundPosition: true,
    backgroundRepeat: true,
    backgroundSize: true,
    gradientColorStops: true,
    borderCollapse: true,
    tableLayout: true,
    listStylePosition: true,
    listStyleType: true,
    textDecorationStyle: true,
    textDecorationThickness: true,
    textUnderlineOffset: true,
    textTransform: true,
    textOverflow: true,
    textIndent: true,
    verticalAlign: true,
    whitespace: true,
    wordBreak: true,
    wordSpacing: true,
    letterSpacing: true,
    textAlign: true,
    fontVariantNumeric: true,
    fontFeatureSettings: true,
    fontVariantCaps: true,
    fontKerning: true,
    fontSmoothing: true,
    fontStyle: true,
    fontFamily: true,
    fontWeight: true,
    fontSize: true,
    lineHeight: true,
    textColor: true,
    backgroundColor: true,
    backgroundOpacity: true,
    borderColor: true,
    borderOpacity: true,
    borderRadius: true,
    borderStyle: true,
    borderWidth: true,
    boxShadow: true,
    opacity: true,
    outline: true,
    ringColor: true,
    ringOffsetColor: true,
    ringOffsetWidth: true,
    ringOpacity: true,
    ringWidth: true,
    fill: true,
    stroke: true,
    strokeWidth: true,
  },
};
