import { type Change, diffLines } from 'diff';

// ANSI color codes for terminal output
export const colors = {
  added: '\\x1b[32m', // green
  removed: '\\x1b[31m', // red
  neutral: '\\x1b[90m', // grey
  reset: '\\x1b[0m'
};

/**
 * Generates a color-coded diff string to visualize the changes between two code blocks.
 * @param originalCode - The original source code.
 * @param updatedCode - The updated source code generated by the AI.
 * @returns A string with ANSI color codes representing the diff.
 */
export function generateDiff(originalCode: string, updatedCode: string): string {
  const differences = diffLines(originalCode, updatedCode);
  let diffOutput = '';

  differences.forEach((part: Change) => {
    if (part.added) {
      diffOutput += `${colors.added}+ ${part.value.replace(/\\n/g, '\\n+ ')}${colors.reset}`;
    } else if (part.removed) {
      diffOutput += `${colors.removed}- ${part.value.replace(/\\n/g, '\\n- ')}${colors.reset}`;
    } else {
      // To keep the output concise, we'll show a limited amount of context
      const lines = part.value.split('\\n');
      if (lines.length > 6) {
        diffOutput += `${colors.neutral}${lines.slice(0, 3).join('\\n')}\\n...\\n${lines.slice(-3).join('\\n')}${colors.reset}\\n`;
      } else {
        diffOutput += `${colors.neutral}${part.value}${colors.reset}`;
      }
    }
  });

  return diffOutput;
} 